version: "4.27.2"

services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations api && python manage.py migrate && gunicorn -k gevent -w 1 backend.wsgi:application -b 0.0.0.0:8000"
    volumes:
      - .:/code
    ports: 
      - "8000:8000"